version: '3'

dotenv: ['.env']

tasks:
  setup:
    desc: start and configure docker containers needed for the development environment
    cmds:
      - task: start-postgres
      - task: start-smtp4dev
      - task: upgrade-database
      - task: insert-test-data

  start-postgres:
    desc: spinup a postgres docker container containing the emerald db
    cmds:
      - docker rm -f postgres
      - docker run -d --rm --name postgres --network=bridge -p 5432:5432 -e POSTGRES_DB=emerald -e POSTGRES_USER=test -e POSTGRES_PASSWORD=test postgres:latest

  start-smtp4dev:
    desc: start a fake email server for development
    cmds:
      - docker rm -f smtp4dev
      - docker run --rm -d --name smtp4dev -p 3000:80 -p 26:25 rnwood/smtp4dev:v3

  install-python-dependencies:
    desc: install python dependencies with pipenv
    cmds:
      - python3.11 -m pipenv install

  upgrade-database:
    desc: upgrade the emerald database schema to the latest alembic version
    cmds:
      - python3.11 -m pipenv run python -m alembic upgrade head

  insert-test-data:
    desc: insert test data in the emerald database
    cmds:
      - python3.11 -m pipenv run python -m develop.insert_test_data
